name: pipeline workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Go to notes2 folder
        run: cd notes2
        
      - name: Install dependencies
        run: npm i

      - name: Check style
        run: npm run lint

      - name: Run npm test
        run: npm run test

      - name: Run npm build
        run: npm run build

  deploy:
    needs: [build_and_test]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' ; '), '#skip')}}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ';'), '#skip') }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with: 
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: false
          DEFAULT_BUMP: patch
